name: install_package
description: Install the package
runs:
  using: "composite"
  steps:
    - name: Upgrade pip
      run: pip install --upgrade pip
      shell: bash
    - name: Install package
      run: pip install .
      shell: bash
