name: run-tests-and-format
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest]
    name: Run tox tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - id: toxenv
        name: Display Python version
        run: |
          output=$(python -c "import sys; print('py{:d}{:d}'.format(*sys.version_info[:2]))")
          echo "::set-output name=toxenv::$output"
        shell: bash
      - name: Install package
        uses: ./.github/actions/install_package
      - name: Install tox
        uses: ./.github/actions/install_tox
        with:
          tox-version: 3.23.1
      - name: Run pytest
        run: tox -e ${{ steps.toxenv.outputs.toxenv }}
        shell: bash
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install tox
        uses: ./.github/actions/install_tox
        with:
          tox-version: 3.23.1
      - name: Run typing testenv
        run: tox -e typing
      - name: Run pypi-description testenv
        run: tox -e pypi-description
      - name: Run manifest testenv
        run: tox -e manifest
      - name: Run precom
        run: tox -e precom
